### ISSUE TITLE
这个方案模糊音怎么设置啊？

### ISSUE THREAD

**Issue by toure00** [bigshans/rime-zrm#1]
![image](https://user-images.githubusercontent.com/33457469/76191488-6ddb9400-621a-11ea-8a7f-d6297959ab19.png)
如图，我这样设置并没有生效

**Comment by bigshans** [comment]
你好，这么迟回复你。
我举个例子，你可以这么设置。
```
    - "derive/^(\\w)g;(\\w)(\\w)$/$1f;$2$3/"
    - "derive/^(\\w)g;(\\w)(\\w)$/$1f;$2/"
    - "derive/^(\\w)g;(\\w)(\\w)$/$1f/"
```
这样就能实现 en ＝> eng 的模糊音。
