### ISSUE TITLE
这个☯️图标是啥意思呢

### ISSUE THREAD

**Issue by ywysuibian** [bigshans/rime-zrm#17]
![image](https://github.com/bigshans/rime-zrm/assets/12655790/0e01b955-6193-4afe-ab64-b78faaab3e46)
有没有大大给答个疑，这图里的第二个选项是啥，完全没有概念。
用的是大大仓库里的myself配置，加了emoji。
先谢过🙏🏻️

**Comment by bigshans** [comment]
如果我没记错的话，这个标志代表自造词，你没有把它加到用户字典里。不过这个应该不影响。

**Comment by ywysuibian** [comment]
> 如果我没记错的话，这个标志代表自造词，你没有把它加到用户字典里。不过这个应该不影响。

感谢回答~，不过恕我小白，请问“自造词”是啥呀？我看带这个图标的字词都是比较偏僻的，我用不上的话有办法关上这个功能么？再次感谢大大。
![image](https://github.com/bigshans/rime-zrm/assets/12655790/c22544dd-be29-4f83-ba33-1453c8b1a174)
![image](https://github.com/bigshans/rime-zrm/assets/12655790/5963f78d-2634-4f74-b0dc-80903c5b768a)

**Comment by bigshans** [comment]
> > 如果我没记错的话，这个标志代表自造词，你没有把它加到用户字典里。不过这个应该不影响。
> 
> 感谢回答~，不过恕我小白，请问“自造词”是啥呀？我看带这个图标的字词都是比较偏僻的，我用不上的话有办法关上这个功能么？再次感谢大大。 ![image](https://private-user-images.githubusercontent.com/12655790/312272523-c22544dd-be29-4f83-ba33-1453c8b1a174.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMjYwODMsIm5iZiI6MTcxMDMyNTc4MywicGF0aCI6Ii8xMjY1NTc5MC8zMTIyNzI1MjMtYzIyNTQ0ZGQtYmUyOS00ZjgzLWJhMzMtMTQ1M2M4YjFhMTc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDEwMjk0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwNzdjYTAyY2NlMTc5OTNmNjZiZWM3OGIzNjE1ODJkOWI0ZmJkMGY4NjE1OGRjYWIyNjFiNTU1ZjM2YmE4ZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CThUsrpyWICwyjeSjh5zt2IBvf3hU66TWAhE_OdjOjU) ![image](https://private-user-images.githubusercontent.com/12655790/312272537-5963f78d-2634-4f74-b0dc-80903c5b768a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMjYwODMsIm5iZiI6MTcxMDMyNTc4MywicGF0aCI6Ii8xMjY1NTc5MC8zMTIyNzI1MzctNTk2M2Y3OGQtMjYzNC00Zjc0LWIwZGMtODA5MDNjNWI3NjhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDEwMjk0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyZDhmNDk4YmUyMWUxOGJhZDFhYjZiY2YwY2YyOTM1NGEwYWU5ZmUxMWQ5Mzg3Y2Q3NGNkOTVlZGM2MmRlZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KAJ7LuCOTK99Hl1hdi4y4Cv5dX9BAUa8MvafPTXeIqc)

自造词就是你词库里没有的词，选了这个词会把它加到你的用户字典里去。你把 schema 里的 `translator/enable_sentence` 或者 `translator/enable_user_dict` （我记不太清了） 关掉就没有了，然后你的输入就是固定字典里的东西了。

**Comment by ywysuibian** [comment]
我回头试试看，感谢！
