### ISSUE TITLE
關於輔助碼按鍵

### ISSUE THREAD

**Issue by aaron2wh** [bigshans/rime-zrm#2]
我已經用分號和單引號作爲二三候選字的按鍵了。與輔助碼的分號衝突了，請問如果改輔助碼按鍵？在那位文件的什麼地方改成怎樣，請幫忙一下。感謝！
比如我想把輔助碼改爲「/」鍵。

另外我想如同RIME自帶那樣用第一次二次單引號來輸入「  和   」改如何修改配置

**Comment by bigshans** [comment]
你好，关于你的两个问题我分别解答。

1. 更改辅助码可能会比较麻烦，你需要将 dict 和 schema 文件里的 `;` 全部替换为 `/` ，但要注意一下在 algebra 和 preedit_format 里转义 `/` 。rime 的正则是 perl 的，可以用 perl 做测试。因为对我的个人配置破坏比较大，所以建议你看看文档尝试一下。
2. 关于标点符号，我个人的处理是输入单引号直接输出 `''` 。我是自己设置有一份字符表的，但这个我比较个人没有传上来。或者你可以尝试参考官方的 rime 配置去做修改，但一般是在 custom.yaml 里做配置。

另外，这里的内容可能对你有所帮助， https://github.com/rime/home/wiki/CustomizationGuide 。谢谢！
