### ISSUE TITLE
抱歉打扰下问个辅码问题

### ISSUE THREAD

**Issue by xp12047** [bigshans/rime-zrm#5]
本人一直使用纯双拼。现在想来练习下辅码，看到这个仓库很开心关键它很新。   
我不懂辅码是怎么安排的然后也查阅了些网站 。那个辅码是怎么定义的，汉字的第一笔和最后一笔吗?我看有些只要三个码有些却要四码?   
希望没有打扰到你。但我似乎搜不到答案。只能这里试着留言了。

**Comment by bigshans** [comment]
可以看这篇：

https://zhuanlan.zhihu.com/p/122866844

辅码是两个码。自然码的辅码其实有点乱，一个字对应有多个辅码很正常，都是便于直觉。我自己用辅码不会特意去记的，如果经常用的话，可能会反查一下辅码。你想要用辅码还是要看字库的，我是清洗过一遍辅码的。市面上大部分输入法不支持辅码，而且自然码的辅码太灵活，有时候反倒没那么好用。

我不太清楚你说的三个码或者四个码是什么情况。原版为了方便输入，特地将完整的辅码拆成一部分一部分的，方便输入。一个字，音码两个，辅码两个，完整的码有四个字长，但辅码可以不用完整输入就找到而已。原版还有一些二字码、三字码，辅码为了让你取得更灵活，会取得非常地零碎。不过大部分输入法用的都是单字音码，偶尔遇到能用辅码的。而且手机上除了 rime 自定义以外，我几乎没有见到过能用辅码的。如果要用来提升打字或者选字速度的话，大概只能是 PC 了吧？

**Comment by xp12047** [comment]
> 可以看这篇：
> 
> https://zhuanlan.zhihu.com/p/122866844
> 
> 辅码是两个码。自然码的辅码其实有点乱，一个字对应有多个辅码很正常，都是便于直觉。我自己用辅码不会特意去记的，如果经常用的话，可能会反查一下辅码。你想要用辅码还是要看字库的，我是清洗过一遍辅码的。市面上大部分输入法不支持辅码，而且自然码的辅码太灵活，有时候反倒没那么好用。
> 
> 我不太清楚你说的三个码或者四个码是什么情况。原版为了方便输入，特地将完整的辅码拆成一部分一部分的，方便输入。一个字，音码两个，辅码两个，完整的码有四个字长，但辅码可以不用完整输入就找到而已。原版还有一些二字码、三字码，辅码为了让你取得更灵活，会取得非常地零碎。不过大部分输入法用的都是单字音码，偶尔遇到能用辅码的。而且手机上除了 rime 自定义以外，我几乎没有见到过能用辅码的。如果要用来提升打字或者选字速度的话，大概只能是 PC 了吧？

也对。我就是无聊了想起来自然码还支持辅码就打算好好研究下。本身我也会些86五笔。一直都是用的纯自然码双拼。谢谢你能回我。
