### ISSUE TITLE
zrm.unique_fm.dict.yaml 的辅助码问题

### ISSUE THREAD

**Issue by sharp-tasting** [bigshans/rime-zrm#6]
辅助码的规则不统一，在输入的时候会产生困惑。
比如“日”，有时用o，有时用r，哪怕是都作为“左偏旁”。

```
晰	xi;ox
晰	xi;ox
晱	uj;ry
晱	uj;ry
``` 

类似的，对于”目“：

```
眼	yj;mg
眼	yj;mg
眽	ml;mp
眽	mo;mp
...
瞃	wf;od
瞄	mc;om
瞅	ib;oq
``` 

我猜测这是为了减少重码，从而把一些字的辅助码进行了 o->r，o->m，另一部分仍然保留 o->o。但是这样规则就乱了，基本无法记忆。
我觉得一个更好的方法是不要r，y，m，把 日、月，目统一到 o 上。unique_fm 的目的是为了防止重码，但辅助码不应该 **unique but random**，而是做到每个字尽可能实现 **unique and by rule** 的辅助码。
自然码辅助码的规则如何唯一确定，可参照 [规则链接1](https://www.liuchuo.net/archives/2847) 和 [规则链接（含键位）2](https://zhuanlan.zhihu.com/p/122866844)

**Comment by bigshans** [comment]
是有这个问题，主要是为了缩减字码，但是程序在处理的时候不能判断字形，于是只能按照辅码出现的顺序进行占用，保证同一个字同一个音下的辅码只有一个。要处理这个问题的话要拆字，如果程序不能很好的处理的话，就要人手工处理了，就看有没有好的库了。

**Comment by sharp-tasting** [comment]
嗯，我试着找出 `unique_fm` 词典里的 日 月 目，发现手动工作量实在太大了，而且这种手动改的性价比是非常非常低的，有些（老实说，是很多）字可能十年都用不到一次。
最经济的方法还是用您的那个 dict 1 当作默认，根据规则选字，时间长了词频慢慢理顺了，重码问题应该也就不太critical了。

嘛，我现在觉得这个问题如果不能自动化的化，基本属于无法修的……

**Comment by sharp-tasting** [comment]
找到了一个抽取汉字偏旁的库，试着改了改发了PR。
